# Generated by Django 5.2.7 on 2025-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='description',
            field=models.TextField(),
        ),
    ]
