# Generated by Django 5.2.7 on 2025-11-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
    ]
