# Generated by Django 5.2.7 on 2025-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videofile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='description',
            field=models.TextField(),
        ),
    ]
